/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ExpositoresRouteImport } from './routes/expositores'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as InstituicaoRouteImport } from './routes/instituicao'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CredencialCodeRouteImport } from './routes/credencial.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCredenciamentoRouteImport } from './routes/_authenticated/admin/credenciamento'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpositoresRoute = ExpositoresRouteImport.update({
  id: '/expositores',
  path: '/expositores',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoRoute = InstituicaoRouteImport.update({
  id: '/instituicao',
  path: '/instituicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CredencialCodeRoute = CredencialCodeRouteImport.update({
  id: '/credencial/$code',
  path: '/credencial/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCredenciamentoRoute =
  AuthenticatedAdminCredenciamentoRouteImport.update({
    id: '/credenciamento',
    path: '/credenciamento',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/credencial/$code': typeof CredencialCodeRoute
  '/admin/credenciamento': typeof AuthenticatedAdminCredenciamentoRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/credencial/$code': typeof CredencialCodeRoute
  '/admin/credenciamento': typeof AuthenticatedAdminCredenciamentoRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/inscricao': typeof InscricaoRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/credencial/$code': typeof CredencialCodeRoute
  '/_authenticated/admin/credenciamento': typeof AuthenticatedAdminCredenciamentoRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/inscricao'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/sitemap.xml'
    | '/admin'
    | '/credencial/$code'
    | '/admin/credenciamento'
    | '/admin/dashboard'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/inscricao'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/sitemap.xml'
    | '/credencial/$code'
    | '/admin/credenciamento'
    | '/admin/dashboard'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contato'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/inscricao'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/credencial/$code'
    | '/_authenticated/admin/credenciamento'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  ExpositoresRoute: typeof ExpositoresRoute
  FaqRoute: typeof FaqRoute
  InscricaoRoute: typeof InscricaoRoute
  InstituicaoRoute: typeof InstituicaoRoute
  ParceirosRoute: typeof ParceirosRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CredencialCodeRoute: typeof CredencialCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expositores': {
      id: '/expositores'
      path: '/expositores'
      fullPath: '/expositores'
      preLoaderRoute: typeof ExpositoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao': {
      id: '/instituicao'
      path: '/instituicao'
      fullPath: '/instituicao'
      preLoaderRoute: typeof InstituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/credencial/$code': {
      id: '/credencial/$code'
      path: '/credencial/$code'
      fullPath: '/credencial/$code'
      preLoaderRoute: typeof CredencialCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credenciamento': {
      id: '/_authenticated/admin/credenciamento'
      path: '/credenciamento'
      fullPath: '/admin/credenciamento'
      preLoaderRoute: typeof AuthenticatedAdminCredenciamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCredenciamentoRoute: typeof AuthenticatedAdminCredenciamentoRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCredenciamentoRoute:
      AuthenticatedAdminCredenciamentoRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  ExpositoresRoute: ExpositoresRoute,
  FaqRoute: FaqRoute,
  InscricaoRoute: InscricaoRoute,
  InstituicaoRoute: InstituicaoRoute,
  ParceirosRoute: ParceirosRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CredencialCodeRoute: CredencialCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
