/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ExpositoresRouteImport } from './routes/expositores'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstituicaoRouteImport } from './routes/instituicao'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpositoresRoute = ExpositoresRouteImport.update({
  id: '/expositores',
  path: '/expositores',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoRoute = InstituicaoRouteImport.update({
  id: '/instituicao',
  path: '/instituicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cursos': typeof CursosRoute
  '/expositores': typeof ExpositoresRoute
  '/faq': typeof FaqRoute
  '/instituicao': typeof InstituicaoRoute
  '/parceiros': typeof ParceirosRoute
  '/programacao': typeof ProgramacaoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cursos'
    | '/expositores'
    | '/faq'
    | '/instituicao'
    | '/parceiros'
    | '/programacao'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CursosRoute: typeof CursosRoute
  ExpositoresRoute: typeof ExpositoresRoute
  FaqRoute: typeof FaqRoute
  InstituicaoRoute: typeof InstituicaoRoute
  ParceirosRoute: typeof ParceirosRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expositores': {
      id: '/expositores'
      path: '/expositores'
      fullPath: '/expositores'
      preLoaderRoute: typeof ExpositoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao': {
      id: '/instituicao'
      path: '/instituicao'
      fullPath: '/instituicao'
      preLoaderRoute: typeof InstituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CursosRoute: CursosRoute,
  ExpositoresRoute: ExpositoresRoute,
  FaqRoute: FaqRoute,
  InstituicaoRoute: InstituicaoRoute,
  ParceirosRoute: ParceirosRoute,
  ProgramacaoRoute: ProgramacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
